config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  #sign up & show
  resources :users, only: [:new, :create, :show] do 
    resource :overview, only: [:show]
    resources :messages, only: [:create, :index]
  end

  #sign in & sign out
  resource :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord

  belongs_to(
    :follower,
    class_name: 'User',
    foreign_key: 'to_user'
  )

  belongs_to(
    :followed,
    class_name: 'User',
    foreign_key: 'from_user'
  )
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to(
    :sender,
    class_name: 'User',
    foreign_key: :sender_id
  )

  belongs_to(
    :receiver,
    class_name: 'User', 
    foreign_key: :receiver_id
  )

  def self.index_by_friend_id(user_id, friend_id)
    return Message.where('sender_id = ? AND receiver_id = ?', user_id, friend_id)
    .or(Message.where('sender_id = ? AND receiver_id = ?', friend_id, user_id)).order("created_at")
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many(
    :followers,
    class_name: 'Friendship',
    foreign_key: 'to_user',
  )

  has_many :followed, through: :followers
  

  has_many(
    :followed,
    class_name: 'Friendship',
    foreign_key: 'from_user'
  )

  has_many :followers, through: :followed

  has_many(
    :sent_messages,
    class_name: 'Message',
    foreign_key: :sender_id
  )

  has_many(
    :received_messages,
    class_name: 'Message',
    foreign_key: :receiver_id
  )

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?

    if user.is_password?(password)
      return user
    else
      return nil
    end
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def is_password?(password) 
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this session"
      redirect_to new_session_url
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = params[:friend_id] ? Message.index_by_friend_id(current_user.id, params[:friend_id]) : []
    
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace(:messages, partial: "messages/messages", locals: { messages: @messages }) }
      format.html { render :index }
    end
  end

  def create
    @receiver = User.find_by(username: params['message']['receiver_name'])
    @message = Message.new({ 
      body: params['message']['body'], 
      receiver_id: @receiver.id,
      sender_id: params[:user_id]
    })

    if @message.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append(:messages, partial: "messages/message", locals: { message: @message })}
        format.html { redirect_to user_messages_url(params[:user_id]) }
      end
    else
      render @message.errors.full_messages
    end
  end

  private

  def message_params
    params.require(:message).permit(:receiver_name, :body)
  end

end

app/controllers/overviews_controller.rb
class OverviewsController < ApplicationController 
  def show
    @user = User.find_by(id: params[:user_id])

    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
      )

    if @user.nil?
      render :new
    else
      login!(@user)
      redirect_to user_url(@user)
    end
  end

  def delete
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    #dummy user
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url
    else
      @user.errors.full_messages
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @friends = @user.followers

    if @user
      render :show
    else
      @user.errors.full_messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LolClient</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<% if message.sender_id == current_user.id %>
  <li class="user_message"><span><%= message.body %><span></li>
<% else %>
  <li class="friend_message"><span><%= message.body %><span><li>
<% end %>

app/views/messages/_messages.html.erb
<ul id="messages" >
<% if messages.length == 0 %>
<% else %>
  <% messages.each do |message| %>
    <% if message.sender_id == current_user.id %>
      <li class="user_message"><span><%= message.body %><span></li>
    <% else %>
      <li class="friend_message"><span><%= message.body %><span></li>
    <% end %>
  <% end %>
<% end %>
</ul>

app/views/messages/_new.html.erb
<%= turbo_frame_tag "new_message" do %>
  <form action="<%= user_messages_url(user_id: user.id) %>" method="POST" id="new_message">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <input type="hidden" name="message[receiver_name]" value="" /> 
    <input type="text" name="message[body]" placeholder="New Message" value="" />
    
    <input class="submit_btn" type="submit" value="SEND" />
  </form>
<% end %>

app/views/messages/index.html.erb
<turbo-frame id="chatbox">
  <ul id="messages">
  <% @messages.each do |message| %>
    <li><%= message.body %></li>
  <% end %>
  </ul>
</turbo-frame>

app/views/overviews/show.html.erb
<%= turbo_frame_tag "main" do %>
  <section class="overview">
    <ul class="main-content-nav">
      <li><%= link_to 'Home', user_path(@user) %></li>
      <li class="main-content-active">Overview</li>
      <li><a>Patch Notes</a></li>
    </ul>
    <video controls>
      Sorry, your browser doesn't support embedded videos.
    </video>
    <video controls>Hello video right here.</video>
    <video controls>Hello video right here.</video>
    <%= image_tag("fiora_wallpaper.jpeg", :alt => "fiora league of legends") %>
    <%= image_tag("fiora_wallpaper.jpeg", :alt => "fiora league of legends") %>
  </section>
<% end %>

app/views/users/_home.html.erb
<section id="home-partial">
  <ul class="main-content-nav">
    <li class="main-content-active">Home</li>
    <li><%= link_to 'Overview', user_overview_path(@user) %></li>
    <li><a>Patch Notes</a></li>
  </ul>
  <h1>Favorite Champsions</h1>
  <ul>
    <li>Kaisa</li>
    <li>Vayne</li>
    <li>Fiora</li>
    <li>Ashe</li>
    <li>Jinx</li>
    <li>Lucian</li>
  </ul>
</section>

app/views/users/new.html.erb
<div class="sign-up">
  <section class="sign-in-info"> 
    <h1 class="title">Login</h1>
    <form class="sign-in-form" action="<%= users_url %>" method="POST">
      <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
      
      <input type="text" id="username" name="user[username]" placeholder="Username">

      <input type="text" id="password" name="user[password]" placeholder="Password">

      <input type="submit-btn" value="Create New Summoner">
    </form>
  </section>
  <%= image_tag("fiora_wallpaper.jpeg", :alt => "fiora league of legends", class: "sign-in-photo") %>
</div>

app/views/users/show.html.erb
<!-- # Need:
#Header
  #Onclick event that will highlight header nav items when they are active. (DONE)
  #onload of show page, Home is active. (DONE)

#Main-content
  #Onclick event that highlights what's showing. Overview is showing first. (DONE)
  #css animation. strike underline! (DONE)

  #Home
    # Get info from League API. Most played champs?
    # win rate?
  #Overview
    # Background-image: preseason
    # video: preseason video
    # image-thumbnail: /dev 
    # image: ranking
    # shop-skins: 2 skins
  #Patch Notes
    # Link/Preview of league's current patch notes
#Chat-feature
  # Highlight user that you are chatting with.
  # Send messages to each other
    # New db to store messages (DONE)
  # Chat window
    # On new user to talk to, add friend to list in chat window. (DONE)
    # add button to remove chat with specific person.

#Missions Feature
-->

<div class="user-show">
  <header>
    <nav>
      <div class="nav-left-side">
        <div id="play-btn">
          <div>Logo</div>
          <div id="pentagon">Play</div>
        </div>
        <ul>
          <li><a class="header-nav-active">Home</a></li>
          <li><a>TFT</a></li>
          <li><a>Clash</a></li>
        </ul>
      </div>

      <ul class="nav-right-side">
        <li><a>Profile</a></li>
        <li><a>Collection</a></li>
        <li><a>Loot</a></li>
        <li><a>Currency</a></li>
        <li><a>Profile</a></li>
      </ul>
    </nav>
  </header>
  <main>
    <section class="main-content">
      <%= turbo_frame_tag "main" do %>
        <%= render "users/home" %>
      <% end %>
      <aside class="minimize">
        <ul>
        </ul>
        <section>
          <h2>Das Kartoffel</h2>
          <section class="chatbox">
            <turbo-frame id="chatbox" src="/users/<%= @user.id %>/messages">
              <ul id="messages"></ul>
            </turbo-frame>
          </section>
          <section class="new-message">
            <%= render "messages/new", user:@user %>
          </section> 
        </section>
      </aside>
    </section>
    <section class="friends">
      <ul class="friends-list">
      <% @friends.each do |friend| %> 
        <li><a href="/users/<%= @user.id %>/messages/?friend_id=<%= friend.id %>"><%= friend.username.capitalize() %></a></li>
      <% end %>
      </ul>

      <ul class="friends-extra">
        <li>Chat
        </li>
        <li>Missions</li>
      </ul>
    </section>
  </main>
</div>